### ISSUE TITLE
any plan to support the new version?

### ISSUE THREAD

**Issue by tgaochn** [NBKRedSpy/CardSurvival-InventoryToBase#2]
Really love this mod!
But the mod is not working in the latest version (update41 in test branch now). 
Is there any plan to support the new version?
Thanks!

**Comment by NBKRedSpy** [comment]
I just uploaded a new version minutes ago that fixes that issue.  :)  
I think it broke in their most recent update to the beta.

It is version 1.1.0, which is in pre-release:
https://github.com/NBKRedSpy/CardSurvival-InventoryToBase/releases/tag/v1.1.0

However, thank you very much for reporting the issue.

**Comment by NBKRedSpy** [comment]
The fix works for me, but please let me know if it works for you as well.  I'll close the ticket at that time.
And I'm very happy to hear you like the mod!  Thanks!

**Comment by tgaochn** [comment]
Great to know that! Thanks!
